#if !canImport(ObjectiveC)
import XCTest

extension DecodingNilTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecodingNilTests = [
        ("testDecodingNulls", testDecodingNulls),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DecodingNilTests.__allTests__DecodingNilTests),
    ]
}
#endif
